### PR TITLE
Adds kitspace content to repo

### LINKED ISSUE #57: [FEATURE REQUEST] Add Kitspace one click pricing
[Kitspace](https://kitspace.org/) is a project that really helps with building open source hardware as it allows you to (when properly implemented) have an almost one click pricing for the PCB and electronics components. If setup by the maintainers it would really decrease uncertainty if the components chosen are the ones that work reliably.

We haven't had to implement it yet but it seems relatively straightforward to implement and lets users have self-autonomy to replicate the work, build upon it and put it in the hands of users.

Examples of very good implementations of this are the [Open book](https://kitspace.org/boards/github.com/joeycastillo/the-open-book/open-book/) and [ebook wing](https://kitspace.org/boards/github.com/joeycastillo/the-open-book/ebook-wing/) projects by @joeycastillo

https://kitspace.org/1-click-bom/
https://github.com/kitspace/1clickBOM#readme

### PR DESCRIPTION
**Pull request by darigovresearch**
Would resolve #57 if merged

### CODE REVIEW

**Comment by kasbah** [comment]
We need an outline on the outline layer (.mil) for the Gerber preview to work. You can load the files into https://tracespace.io/view/ to have a look. (go to the "layers" view on top and select "Show filenames" on the bottom left). 

image

**Comment by darigovresearch** [comment]
@midopple do you know how to generate the outline on the .mil file for the Gerbers?

**Comment by BarbourSmith** [comment]
Should I hold off on merging this until the outline layer is there?

**Comment by darigovresearch** [comment]
@BarbourSmith from our understanding the content of the .yml & .csv are correct, it's the gerbers which is the issue. There is an additional step which @kasbah does on their side for it to be previewed on the site.

Have created a separate issue (https://github.com/MaslowCNC/Electronics/issues/63) to try to see if anyone else from the community can resolve that side of the issue.

**Comment by BarbourSmith** [comment]
Great, I'll merge this now and we can add to it in the future if need be.

**Pull request merged**
